version: '3.8'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: web_python
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}


    depends_on:
      - reverse-proxy
      - ingress-proxy
      - db
    env_file:
      - .env


  db:
    image: mysql:8
    container_name: db_mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_HOST=%
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - "3306:3306"

    depends_on:
      - reverse-proxy
      - ingress-proxy

    env_file:
      - .env


include:
  - path:
     - proxy.yaml


